### PR TITLE
Fix a typo: you're installed -> you've installed

### PR DESCRIPTION
**Pull request by PoziWorld**

### CODE REVIEW

**Comment by caitmuenster** [comment]
Thanks, @Poziworld! We've added your contributions to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition#July_2018). :) 

Would you be interested in creating an account on [mozillians.org](https://mozillians.org/)? I'd be happy to vouch for you!

**Comment by PoziWorld** [comment]
@caitmuenster, should I go and sign up myself or do you need to invite me first?

**Comment by ExE-Boss** [comment]
You can sign up yourself.

**Comment by PoziWorld** [comment]
@ExE-Boss, thanks!

https://mozillians.org/u/PoziWorld/

**Comment by caitmuenster** [comment]
Thanks, @ExE-Boss! @PoziWorld, you're vouched! Welcome onboard!

**Comment by PoziWorld** [comment]
Thank you, @caitmuenster! I appreciate it.

**Pull request merged**
