### PR TITLE
Save 60% or more by switching to arrays today!

### PR DESCRIPTION
**Pull request by bfred-it**
I saw that the whole JSON file repeats the same keys so I thought of shortening it to arrays. This halves the size of the file and browser memory usage. JSDoc still describes the two indexes so IDEs don't get confused.

JSDoc format found here: https://github.com/jsdoc3/jsdoc/issues/1073#issuecomment-167204327

Failing build is due to #41

### CODE REVIEW

**Comment by bfred-it** [comment]
If there's interest I can resolve the conflicts.

**Comment by bfred-it** [comment]
Actually there’s an even more efficient solution to this by using defaults for the most common situation. If PRs are considered I’ll replace this one.

**Comment by ahmadassaf** [comment]
I like this PR but i think now with the new devtools support this will not work as the api metadata contains more info

```js
        "devtools": {
          "inspectedWindow": {
            "eval": {
              "minArgs": 1,
              "maxArgs": 2
            }
          },
          "panels": {
            "create": {
              "minArgs": 3,
              "maxArgs": 3,
              "singleCallbackArg": true
            }
          }
        },
```

**Comment by bfred-it** [comment]
That’s ok, it could be minified to [3, 3, true] (and then whatever comes later). The solution I was thinking about was to automatically apply these optimizations in the gruntfile, so the repo can have the human-readable json and the outputted file can be small.

**Comment by ExE-Boss** [comment]
Or, make the third argument an optional options object, similarly to what ESLint does.

**Comment by james-cnz** [comment]
For what it's worth, I looked at how much could be saved on the JSON file (as it is at the moment) with various partial measures.

Methods are currently described in the JSON file like follows:
  "methodName": {
    "minArgs": n,
    "maxArgs": n,
    "fallbackToNoCallback": true
  },

Removing line breaks and indents from within the method description, like follows, saves ~26%
  "methodName": {"minArgs": n, "maxArgs": n, "fallbackToNoCallback": true},

Removing quote marks from within the method description, like follows, further saves ~6%
  "methodName": {minArgs: n, maxArgs: n, fallbackToNoCallback: true},

Using an array for the number of arguments, like follows, further saves ~14%
  "methodName": {args: [n, n], fallbackToNoCallback: true},

Using an array for the whole method description, like follows (and as per the PR), further saves ~13%
  "methodName": [n, n, true],

This adds up to a total saving of ~59%.

**Comment by ExE-Boss** [comment]
> Removing quote marks from within the method description

That’s no longer valid JSON.

**Comment by Rob--W** [comment]
>> Removing quote marks from within the method description
>
> That’s no longer valid JSON.

That is not a problem, because the JSON data is embedded as a JavaScript object literal in the polyfill.

**Comment by bfred-it** [comment]
These optimizations can be done at bundling time. @Rob--W is it worth looking into it or should I abandon this PR?

**Comment by rpl** [comment]
@bfred-it we were still changing the metadata for fixing issues specific to some of the API methods (and also add more of the API methods and namespaces) and so I preferred to defer big changes to the api-metadata json file format, nevertheless I still think that reducing the size of the JSON api metadata could be a very good thing.

If we can leave the api-metadata.json file in a human-readable format in the source repo, then this sounds even better to me, the optimizations we need to "make these JSON data smaller in memory" can be definitely be part of the build process.

**Comment by james-cnz** [comment]
I didn't know the quotes are required in JSON.  I guess this needn't be problem, as Rob--W says, if the "JSON" file is considered to be a fragment of JavaScript, rather than JSON.  It might be nice to keep it as JSON, anyway, to allow easier automatic validation, though?

Personally, I don't like the idea of adding custom optimisations into the build process, because this would add a little bit more complexity, and I struggle to understand the polyfill as it is.

With regards to documenting arrays with differently-typed elements in JSDoc, further down in the comment linked from the original post, I think it says this is a "work around",  not official JSDoc?  So support for validating this might be variable?

It's also occurred to me, if the JavaScript is to be patched during the build process, to match the changes to the JSON, this could be fragile?  Whereas if the changes are made to the JavaScript source, this would reduce readability.

I think removing line breaks and the associated indents from within the method descriptions, together with using an array for the number of arguments, would save ~40%, without breaking the JSON or requiring any change to the build process?

Alternatively, looking at how much could be saved by removing comments from browser-polyfill.js, I think this works out as equivalent to ~96% of the size of the JSON file?  Could doing this in the build process be an easy win?

**Comment by ExE-Boss** [comment]
I made PR #141 to always minify `api-metadata.json` when importing it.

**Pull request closed without merging**
