### PR TITLE
chore(deps): Updated chromedriver to version 78.0.1

### PR DESCRIPTION
**Pull request by Manvel**
Fix chromedriver failure triggered by Travis CI. See -> https://travis-ci.org/mozilla/webextension-polyfill/builds/604662201#L568

### CODE REVIEW

**Comment by Rob--W** [comment]
Thanks!

**Comment by caitmuenster** [comment]
Thanks so much, @Manvel! ✨ Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition). 

Would you be interested in creating a profile on [mozillians.org](https://mozillians.org/)? I'd be happy to vouch for you!

**Comment by Manvel** [comment]
Thank you @caitmuenster 🙂

> Would you be interested in creating a profile on mozillians.org? 

Sure, link to the profile -> https://mozillians.org/en-US/u/saroyanm

**Comment by caitmuenster** [comment]
Sorry, @Manvel, that link didn't work for me and I wasn't able to look you up in the directory. :( Want to try again?

**Comment by Manvel** [comment]
> Sorry, @Manvel, that link didn't work for me and I wasn't able to look you up in the directory. :( Want to try again?

That's strange, not sure why it has gone :/ I have created a new one anyway, should be accessible now using same link: https://mozillians.org/en-US/u/saroyanm 🤞

**Comment by Manvel** [comment]
@caitmuenster and now it's gone again :/ That's weird.

**Comment by caitmuenster** [comment]
@Manvel looks like that last one stuck -- I was just able to vouch for you. 🎉

Thanks again for the patch and welcome onboard! We look forward to seeing you around.

**Pull request merged**
