### PR TITLE
Export browser object

### PR DESCRIPTION
**Pull request by collinsauve**

### CODE REVIEW

**Comment by collinsauve** [comment]
For issue https://github.com/mozilla/webextension-polyfill/issues/29

**Comment by BigBlueHat** [comment]
Might be best to squash the commits to make review easier. Not sure if something like UMD is needed in this case, but it would be very nice to `require('webextension-polyfill')` in the future.

Great idea @collinsauve

**Comment by collinsauve** [comment]
Thanks @BigBlueHat, squashed.

**Comment by josephfrazier** [comment]
https://github.com/mozilla/webextension-polyfill/pull/17 also has some changes that make it possible to `npm install` from github and use with a bundler. If it's merged and subsequently published to npm, it will also be possible to `npm install` the pre-built `dist/` files, so that no build tools or bundlers are needed.

---

If you'd like, you can go ahead and install it from github using:

    npm install --save https://github.com/mozilla/webextension-polyfill#99faff94ffbf03094361875a10e1692acc4b8662

**Comment by rpl** [comment]
Hi @collinsauve,
As mentioned by @josephfrazier, in #17 we are starting to wrap the built file as an UMD module, and so the polyfill should now be able to work as a commonjs module (and there is also a new test case for it).

I'm closing this PR because we just merged #17 and it should already cover this (feel free to open a new issue and/or pull request if anything is missing, so that we can work on them as "follow-ups" of #17).

My apologies for the duplicated effort and the waiting time.

**Pull request closed without merging**
