### PR TITLE
chore: Replace post-processed warning message with single-line string literal

### PR DESCRIPTION
**Pull request by ExE-Boss**
See @rpl’s comment in https://github.com/mozilla/webextension-polyfill/pull/142#issuecomment-405595998.

### CODE REVIEW

**Comment by Rob--W** [comment]
Thanks for this contribution! Now we have documented the contribution guidelines more clearly, so please consider amending the commit message to adhere to the guidelines: https://github.com/mozilla/webextension-polyfill/blob/master/CONTRIBUTING.md#writing-commit-messages

(we can also amend the comment ourselves before merging, but I'd like to give you the opportunity to do it yourself)

**Comment by ExE-Boss** [comment]
review?(@Rob--W): Is this the correct name for this PR?

**Comment by ExE-Boss** [comment]
`chore: Replace post-processed warning message with single-line string literal` looks good.

**Comment by Rob--W** [comment]
Please amend the title and update the branch. Then CI will automatically run tests and if they are green I will merge the PR.

**Comment by ExE-Boss** [comment]
@Rob--W Done.

**Comment by Rob--W** [comment]
Thanks for your PR!

I have merged it as follows:

```
git checkout master
git pull upstream master
git fetch upstream refs/pull/152/head
git merge FETCH_HEAD
git push upstream master
```

**Pull request merged**
